export const REQUEST_PARKS = "REQUEST_PARKS"
export const GET_PARKS_SUCCESS = "GET_PARKS_SUCCESS"
export const GET_PARKS_FAILURE = "GET_PARKS_FAILURE"
export const REQUEST_TO_POST_PARK = "REQUEST_TO_POST_PARK"